mex -v -I/usr/include/vle-1.0 -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/glib-2.0 ...
     -I/usr/lib/x86_64-linux-gnu/glib-2.0/include ...
     -I/usr/include/sigc++-2.0 ...
     -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include ...
     -I/usr/include/libxml2 ...
     -I/usr/include/boost ...
     -I/usr/include ...
     -I/usr/include/c++ ...
     -I. ...
     ./matlabvle_interface_mex.cpp ...
     ./convert.cpp ...
     -L. ...
     -L/usr/lib ...
     -L/usr/lib/x86_64-linux-gnu ...
     -L/usr/lib/gcc/x86_64-linux-gnu/4.6 ...
     -L/lib ...
     -lboost_system ...
     -lvlemanager-1.0 ...
     -lvleutils-1.0...
     -lvlevpz-1.0...
     -lvledevs-1.0...
     -lvleoov-1.0...
     -lvlevalue-1.0...
     -outdir ./../build
